skipsdist = true

envlist = ["unused-code", "backend-unittests"]

[env.unused-code]
deps = ["python-utility-scripts"]
commands = [["pyutils-unusedcode"]]

[env.backend-unittests]
deps = ["uv"]
commands = [["uv", "run", "--group", "tests", "pytest", "backend/tests"]]
